# SPDX-License-Identifier: BSD-2-Clause
"""Extract the upstream Tier-1 context tables without changing their indexing."""
import re
from pathlib import Path


def generate():
    root = Path(__file__).resolve().parents[2]
    source = (root / "src/lib/openjp2/t1_luts.h").read_text()
    notice = (root / "experimental/opencl/t1_decode.cl").read_text().split("/* SPDX")[0]
    result = notice + "/* Generated by generate_context_tables.py from upstream t1_luts.h. */\n"
    for name, count in (("lut_ctxno_zc", 2048), ("lut_ctxno_sc", 256), ("lut_spb", 256)):
        match = re.search(r"static const OPJ_BYTE " + name + r"\[" + str(count) + r"\] = \{(.*?)\};", source, re.S)
        if not match:
            raise ValueError("Missing upstream table: " + name)
        result += "__constant uchar " + name + "[" + str(count) + "] = {" + match[1] + "};\n"
    for name in ("lut_nmsedec_sig", "lut_nmsedec_sig0", "lut_nmsedec_ref", "lut_nmsedec_ref0"):
        match = re.search(r"static const OPJ_INT16 " + name + r"\[1U << T1_NMSEDEC_BITS\] = \{(.*?)\};", source, re.S)
        if not match:
            raise ValueError("Missing upstream table: " + name)
        result += "__constant short " + name + "[128] = {" + match[1] + "};\n"
    return result


if __name__ == "__main__":
    Path(__file__).with_name("context_tables.clh").write_text(generate(), newline="\n")
