# SPDX-License-Identifier: BSD-2-Clause
"""Convert upstream's pointer-linked MQ state table into OpenCL integer indices."""
from pathlib import Path
import re


def generate():
    directory = Path(__file__).resolve().parent
    source = (directory / "../../src/lib/openjp2/mqc.c").resolve().read_text()
    rows = re.findall(r"\{(0x[0-9a-f]+), ([01]), &mqc_states\[(\d+)\], &mqc_states\[(\d+)\]\}", source)
    if len(rows) != 94:
        raise RuntimeError("Unexpected upstream MQ table shape")
    notice = source[:source.index("*/") + 2]
    body = "\n".join("    (uint4)(" + ", ".join(row) + ")," for row in rows)
    return notice + "\n/* Generated by generate_mq_tables.py from mqc.c; do not edit. */\n__constant uint4 mq_states[94] = {\n" + body + "\n};\n"


if __name__ == "__main__":
    Path(__file__).with_name("mq_states.clh").write_bytes(generate().encode("utf-8"))
