/* SPDX-License-Identifier: BSD-2-Clause
 * NVIDIA implementation with independent serial entropy coders, shared packed
 * flags, packed MQ states and CLZ-based renormalization.
 * Arithmetic and notices below derive from the existing OpenJPEG/OpenCL path.
 */
#include <cuda_runtime.h>
typedef unsigned char uchar;
typedef unsigned int uint;
struct FlagArray {
    unsigned *base;
    __device__ __forceinline__ unsigned& operator[](int i) const { return base[i]; }
};
/*
 * The copyright in this software is being made available under the 2-clauses
 * BSD License, included below. This software may be subject to other third
 * party and contributor rights, including patent rights, and no such rights
 * are granted under this license.
 *
 * Copyright (c) 2002-2014, Universite catholique de Louvain (UCL), Belgium
 * Copyright (c) 2002-2014, Professor Benoit Macq
 * Copyright (c) 2001-2003, David Janssens
 * Copyright (c) 2002-2003, Yannick Verschueren
 * Copyright (c) 2003-2007, Francois-Olivier Devaux
 * Copyright (c) 2003-2014, Antonin Descampe
 * Copyright (c) 2005, Herve Drolon, FreeImage Team
 * Copyright (c) 2008, Jerome Fimes, Communications & Systemes <jerome.fimes@c-s.fr>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS `AS IS'
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
/* Generated by generate_mq_tables.py from mqc.c; do not edit. */
__device__ __constant__ uint mq_states[94] = {
    0x3045601u,0x2075601u,0xc083401u,0xd0b3401u,0x120c1801u,0x130f1801u,0x18100ac1u,0x19130ac1u,
    0x3a140521u,0x3b170521u,0x42980221u,0x439b0221u,0xd1c5601u,0xc1f5601u,0x1c205401u,0x1d235401u,
    0x1c244801u,0x1d274801u,0x1c283801u,0x1d2b3801u,0x222c3001u,0x232f3001u,0x24302401u,0x25332401u,
    0x28341c01u,0x29371c01u,0x2a741601u,0x2b771601u,0x1d3c5601u,0x1c3f5601u,0x1c405401u,0x1d435401u,
    0x1e445101u,0x1f475101u,0x20484801u,0x214b4801u,0x224c3801u,0x234f3801u,0x24503401u,0x25533401u,
    0x26543001u,0x27573001u,0x26582801u,0x275b2801u,0x285c2401u,0x295f2401u,0x2a602201u,0x2b632201u,
    0x2c641c01u,0x2d671c01u,0x2e681801u,0x2f6b1801u,0x306c1601u,0x316f1601u,0x32701401u,0x33731401u,
    0x34741201u,0x35771201u,0x36781101u,0x377b1101u,0x387c0ac1u,0x397f0ac1u,0x3a8009c1u,0x3b8309c1u,
    0x3c8408a1u,0x3d8708a1u,0x3e880521u,0x3f8b0521u,0x408c0441u,0x418f0441u,0x429002a1u,0x439302a1u,
    0x44940221u,0x45970221u,0x46980141u,0x479b0141u,0x489c0111u,0x499f0111u,0x4aa00085u,0x4ba30085u,
    0x4ca40049u,0x4da70049u,0x4ea80025u,0x4fab0025u,0x50ac0015u,0x51af0015u,0x52b00009u,0x53b30009u,
    0x54b40005u,0x55b70005u,0x56b40001u,0x57b70001u,0x5cb85601u,0x5dbb5601u
};

/*
 * The copyright in this software is being made available under the 2-clauses
 * BSD License, included below. This software may be subject to other third
 * party and contributor rights, including patent rights, and no such rights
 * are granted under this license.
 *
 * Copyright (c) 2002-2014, Universite catholique de Louvain (UCL), Belgium
 * Copyright (c) 2002-2014, Professor Benoit Macq
 * Copyright (c) 2001-2003, David Janssens
 * Copyright (c) 2002-2003, Yannick Verschueren
 * Copyright (c) 2003-2007, Francois-Olivier Devaux
 * Copyright (c) 2003-2014, Antonin Descampe
 * Copyright (c) 2005, Herve Drolon, FreeImage Team
 * Copyright (c) 2007, Callum Lerwick <seg@haxxed.com>
 * Copyright (c) 2012, Carl Hetherington
 * Copyright (c) 2017, IntoPIX SA <support@intopix.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS `AS IS'
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
/* Generated by generate_context_tables.py from upstream t1_luts.h. */
__device__ __constant__ uchar lut_ctxno_zc[2048] = {
    0, 1, 3, 3, 1, 2, 3, 3, 5, 6, 7, 7, 6, 6, 7, 7, 0, 1, 3, 3, 1, 2, 3, 3, 5, 6, 7, 7, 6, 6, 7, 7,
    5, 6, 7, 7, 6, 6, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 5, 6, 7, 7, 6, 6, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8,
    1, 2, 3, 3, 2, 2, 3, 3, 6, 6, 7, 7, 6, 6, 7, 7, 1, 2, 3, 3, 2, 2, 3, 3, 6, 6, 7, 7, 6, 6, 7, 7,
    6, 6, 7, 7, 6, 6, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 6, 6, 7, 7, 6, 6, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8,
    3, 3, 4, 4, 3, 3, 4, 4, 7, 7, 7, 7, 7, 7, 7, 7, 3, 3, 4, 4, 3, 3, 4, 4, 7, 7, 7, 7, 7, 7, 7, 7,
    7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8,
    3, 3, 4, 4, 3, 3, 4, 4, 7, 7, 7, 7, 7, 7, 7, 7, 3, 3, 4, 4, 3, 3, 4, 4, 7, 7, 7, 7, 7, 7, 7, 7,
    7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8,
    1, 2, 3, 3, 2, 2, 3, 3, 6, 6, 7, 7, 6, 6, 7, 7, 1, 2, 3, 3, 2, 2, 3, 3, 6, 6, 7, 7, 6, 6, 7, 7,
    6, 6, 7, 7, 6, 6, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 6, 6, 7, 7, 6, 6, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8,
    2, 2, 3, 3, 2, 2, 3, 3, 6, 6, 7, 7, 6, 6, 7, 7, 2, 2, 3, 3, 2, 2, 3, 3, 6, 6, 7, 7, 6, 6, 7, 7,
    6, 6, 7, 7, 6, 6, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 6, 6, 7, 7, 6, 6, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8,
    3, 3, 4, 4, 3, 3, 4, 4, 7, 7, 7, 7, 7, 7, 7, 7, 3, 3, 4, 4, 3, 3, 4, 4, 7, 7, 7, 7, 7, 7, 7, 7,
    7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8,
    3, 3, 4, 4, 3, 3, 4, 4, 7, 7, 7, 7, 7, 7, 7, 7, 3, 3, 4, 4, 3, 3, 4, 4, 7, 7, 7, 7, 7, 7, 7, 7,
    7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8,
    0, 1, 5, 6, 1, 2, 6, 6, 3, 3, 7, 7, 3, 3, 7, 7, 0, 1, 5, 6, 1, 2, 6, 6, 3, 3, 7, 7, 3, 3, 7, 7,
    3, 3, 7, 7, 3, 3, 7, 7, 4, 4, 7, 7, 4, 4, 7, 7, 3, 3, 7, 7, 3, 3, 7, 7, 4, 4, 7, 7, 4, 4, 7, 7,
    1, 2, 6, 6, 2, 2, 6, 6, 3, 3, 7, 7, 3, 3, 7, 7, 1, 2, 6, 6, 2, 2, 6, 6, 3, 3, 7, 7, 3, 3, 7, 7,
    3, 3, 7, 7, 3, 3, 7, 7, 4, 4, 7, 7, 4, 4, 7, 7, 3, 3, 7, 7, 3, 3, 7, 7, 4, 4, 7, 7, 4, 4, 7, 7,
    5, 6, 8, 8, 6, 6, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 5, 6, 8, 8, 6, 6, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8,
    7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8,
    6, 6, 8, 8, 6, 6, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 6, 6, 8, 8, 6, 6, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8,
    7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8,
    1, 2, 6, 6, 2, 2, 6, 6, 3, 3, 7, 7, 3, 3, 7, 7, 1, 2, 6, 6, 2, 2, 6, 6, 3, 3, 7, 7, 3, 3, 7, 7,
    3, 3, 7, 7, 3, 3, 7, 7, 4, 4, 7, 7, 4, 4, 7, 7, 3, 3, 7, 7, 3, 3, 7, 7, 4, 4, 7, 7, 4, 4, 7, 7,
    2, 2, 6, 6, 2, 2, 6, 6, 3, 3, 7, 7, 3, 3, 7, 7, 2, 2, 6, 6, 2, 2, 6, 6, 3, 3, 7, 7, 3, 3, 7, 7,
    3, 3, 7, 7, 3, 3, 7, 7, 4, 4, 7, 7, 4, 4, 7, 7, 3, 3, 7, 7, 3, 3, 7, 7, 4, 4, 7, 7, 4, 4, 7, 7,
    6, 6, 8, 8, 6, 6, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 6, 6, 8, 8, 6, 6, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8,
    7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8,
    6, 6, 8, 8, 6, 6, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 6, 6, 8, 8, 6, 6, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8,
    7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 8, 8,
    0, 1, 3, 3, 1, 2, 3, 3, 5, 6, 7, 7, 6, 6, 7, 7, 0, 1, 3, 3, 1, 2, 3, 3, 5, 6, 7, 7, 6, 6, 7, 7,
    5, 6, 7, 7, 6, 6, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 5, 6, 7, 7, 6, 6, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8,
    1, 2, 3, 3, 2, 2, 3, 3, 6, 6, 7, 7, 6, 6, 7, 7, 1, 2, 3, 3, 2, 2, 3, 3, 6, 6, 7, 7, 6, 6, 7, 7,
    6, 6, 7, 7, 6, 6, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 6, 6, 7, 7, 6, 6, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8,
    3, 3, 4, 4, 3, 3, 4, 4, 7, 7, 7, 7, 7, 7, 7, 7, 3, 3, 4, 4, 3, 3, 4, 4, 7, 7, 7, 7, 7, 7, 7, 7,
    7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8,
    3, 3, 4, 4, 3, 3, 4, 4, 7, 7, 7, 7, 7, 7, 7, 7, 3, 3, 4, 4, 3, 3, 4, 4, 7, 7, 7, 7, 7, 7, 7, 7,
    7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8,
    1, 2, 3, 3, 2, 2, 3, 3, 6, 6, 7, 7, 6, 6, 7, 7, 1, 2, 3, 3, 2, 2, 3, 3, 6, 6, 7, 7, 6, 6, 7, 7,
    6, 6, 7, 7, 6, 6, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 6, 6, 7, 7, 6, 6, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8,
    2, 2, 3, 3, 2, 2, 3, 3, 6, 6, 7, 7, 6, 6, 7, 7, 2, 2, 3, 3, 2, 2, 3, 3, 6, 6, 7, 7, 6, 6, 7, 7,
    6, 6, 7, 7, 6, 6, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 6, 6, 7, 7, 6, 6, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8,
    3, 3, 4, 4, 3, 3, 4, 4, 7, 7, 7, 7, 7, 7, 7, 7, 3, 3, 4, 4, 3, 3, 4, 4, 7, 7, 7, 7, 7, 7, 7, 7,
    7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8,
    3, 3, 4, 4, 3, 3, 4, 4, 7, 7, 7, 7, 7, 7, 7, 7, 3, 3, 4, 4, 3, 3, 4, 4, 7, 7, 7, 7, 7, 7, 7, 7,
    7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8,
    0, 3, 1, 4, 3, 6, 4, 7, 1, 4, 2, 5, 4, 7, 5, 7, 0, 3, 1, 4, 3, 6, 4, 7, 1, 4, 2, 5, 4, 7, 5, 7,
    1, 4, 2, 5, 4, 7, 5, 7, 2, 5, 2, 5, 5, 7, 5, 7, 1, 4, 2, 5, 4, 7, 5, 7, 2, 5, 2, 5, 5, 7, 5, 7,
    3, 6, 4, 7, 6, 8, 7, 8, 4, 7, 5, 7, 7, 8, 7, 8, 3, 6, 4, 7, 6, 8, 7, 8, 4, 7, 5, 7, 7, 8, 7, 8,
    4, 7, 5, 7, 7, 8, 7, 8, 5, 7, 5, 7, 7, 8, 7, 8, 4, 7, 5, 7, 7, 8, 7, 8, 5, 7, 5, 7, 7, 8, 7, 8,
    1, 4, 2, 5, 4, 7, 5, 7, 2, 5, 2, 5, 5, 7, 5, 7, 1, 4, 2, 5, 4, 7, 5, 7, 2, 5, 2, 5, 5, 7, 5, 7,
    2, 5, 2, 5, 5, 7, 5, 7, 2, 5, 2, 5, 5, 7, 5, 7, 2, 5, 2, 5, 5, 7, 5, 7, 2, 5, 2, 5, 5, 7, 5, 7,
    4, 7, 5, 7, 7, 8, 7, 8, 5, 7, 5, 7, 7, 8, 7, 8, 4, 7, 5, 7, 7, 8, 7, 8, 5, 7, 5, 7, 7, 8, 7, 8,
    5, 7, 5, 7, 7, 8, 7, 8, 5, 7, 5, 7, 7, 8, 7, 8, 5, 7, 5, 7, 7, 8, 7, 8, 5, 7, 5, 7, 7, 8, 7, 8,
    3, 6, 4, 7, 6, 8, 7, 8, 4, 7, 5, 7, 7, 8, 7, 8, 3, 6, 4, 7, 6, 8, 7, 8, 4, 7, 5, 7, 7, 8, 7, 8,
    4, 7, 5, 7, 7, 8, 7, 8, 5, 7, 5, 7, 7, 8, 7, 8, 4, 7, 5, 7, 7, 8, 7, 8, 5, 7, 5, 7, 7, 8, 7, 8,
    6, 8, 7, 8, 8, 8, 8, 8, 7, 8, 7, 8, 8, 8, 8, 8, 6, 8, 7, 8, 8, 8, 8, 8, 7, 8, 7, 8, 8, 8, 8, 8,
    7, 8, 7, 8, 8, 8, 8, 8, 7, 8, 7, 8, 8, 8, 8, 8, 7, 8, 7, 8, 8, 8, 8, 8, 7, 8, 7, 8, 8, 8, 8, 8,
    4, 7, 5, 7, 7, 8, 7, 8, 5, 7, 5, 7, 7, 8, 7, 8, 4, 7, 5, 7, 7, 8, 7, 8, 5, 7, 5, 7, 7, 8, 7, 8,
    5, 7, 5, 7, 7, 8, 7, 8, 5, 7, 5, 7, 7, 8, 7, 8, 5, 7, 5, 7, 7, 8, 7, 8, 5, 7, 5, 7, 7, 8, 7, 8,
    7, 8, 7, 8, 8, 8, 8, 8, 7, 8, 7, 8, 8, 8, 8, 8, 7, 8, 7, 8, 8, 8, 8, 8, 7, 8, 7, 8, 8, 8, 8, 8,
    7, 8, 7, 8, 8, 8, 8, 8, 7, 8, 7, 8, 8, 8, 8, 8, 7, 8, 7, 8, 8, 8, 8, 8, 7, 8, 7, 8, 8, 8, 8, 8
};
__device__ __constant__ uchar lut_ctxno_sc[256] = {
    0x9, 0x9, 0xa, 0xa, 0x9, 0x9, 0xa, 0xa, 0xc, 0xc, 0xd, 0xb, 0xc, 0xc, 0xd, 0xb,
    0x9, 0x9, 0xa, 0xa, 0x9, 0x9, 0xa, 0xa, 0xc, 0xc, 0xb, 0xd, 0xc, 0xc, 0xb, 0xd,
    0xc, 0xc, 0xd, 0xd, 0xc, 0xc, 0xb, 0xb, 0xc, 0x9, 0xd, 0xa, 0x9, 0xc, 0xa, 0xb,
    0xc, 0xc, 0xb, 0xb, 0xc, 0xc, 0xd, 0xd, 0xc, 0x9, 0xb, 0xa, 0x9, 0xc, 0xa, 0xd,
    0x9, 0x9, 0xa, 0xa, 0x9, 0x9, 0xa, 0xa, 0xc, 0xc, 0xd, 0xb, 0xc, 0xc, 0xd, 0xb,
    0x9, 0x9, 0xa, 0xa, 0x9, 0x9, 0xa, 0xa, 0xc, 0xc, 0xb, 0xd, 0xc, 0xc, 0xb, 0xd,
    0xc, 0xc, 0xd, 0xd, 0xc, 0xc, 0xb, 0xb, 0xc, 0x9, 0xd, 0xa, 0x9, 0xc, 0xa, 0xb,
    0xc, 0xc, 0xb, 0xb, 0xc, 0xc, 0xd, 0xd, 0xc, 0x9, 0xb, 0xa, 0x9, 0xc, 0xa, 0xd,
    0xa, 0xa, 0xa, 0xa, 0xa, 0xa, 0xa, 0xa, 0xd, 0xb, 0xd, 0xb, 0xd, 0xb, 0xd, 0xb,
    0xa, 0xa, 0x9, 0x9, 0xa, 0xa, 0x9, 0x9, 0xd, 0xb, 0xc, 0xc, 0xd, 0xb, 0xc, 0xc,
    0xd, 0xd, 0xd, 0xd, 0xb, 0xb, 0xb, 0xb, 0xd, 0xa, 0xd, 0xa, 0xa, 0xb, 0xa, 0xb,
    0xd, 0xd, 0xc, 0xc, 0xb, 0xb, 0xc, 0xc, 0xd, 0xa, 0xc, 0x9, 0xa, 0xb, 0x9, 0xc,
    0xa, 0xa, 0x9, 0x9, 0xa, 0xa, 0x9, 0x9, 0xb, 0xd, 0xc, 0xc, 0xb, 0xd, 0xc, 0xc,
    0xa, 0xa, 0xa, 0xa, 0xa, 0xa, 0xa, 0xa, 0xb, 0xd, 0xb, 0xd, 0xb, 0xd, 0xb, 0xd,
    0xb, 0xb, 0xc, 0xc, 0xd, 0xd, 0xc, 0xc, 0xb, 0xa, 0xc, 0x9, 0xa, 0xd, 0x9, 0xc,
    0xb, 0xb, 0xb, 0xb, 0xd, 0xd, 0xd, 0xd, 0xb, 0xa, 0xb, 0xa, 0xa, 0xd, 0xa, 0xd
};
__device__ __constant__ uchar lut_spb[256] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
    0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
    0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
    0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
    1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
    0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1
};
__device__ __constant__ short lut_nmsedec_sig[128] = {
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0180, 0x0300, 0x0480, 0x0600, 0x0780, 0x0900, 0x0a80,
    0x0c00, 0x0d80, 0x0f00, 0x1080, 0x1200, 0x1380, 0x1500, 0x1680,
    0x1800, 0x1980, 0x1b00, 0x1c80, 0x1e00, 0x1f80, 0x2100, 0x2280,
    0x2400, 0x2580, 0x2700, 0x2880, 0x2a00, 0x2b80, 0x2d00, 0x2e80,
    0x3000, 0x3180, 0x3300, 0x3480, 0x3600, 0x3780, 0x3900, 0x3a80,
    0x3c00, 0x3d80, 0x3f00, 0x4080, 0x4200, 0x4380, 0x4500, 0x4680,
    0x4800, 0x4980, 0x4b00, 0x4c80, 0x4e00, 0x4f80, 0x5100, 0x5280,
    0x5400, 0x5580, 0x5700, 0x5880, 0x5a00, 0x5b80, 0x5d00, 0x5e80,
    0x6000, 0x6180, 0x6300, 0x6480, 0x6600, 0x6780, 0x6900, 0x6a80,
    0x6c00, 0x6d80, 0x6f00, 0x7080, 0x7200, 0x7380, 0x7500, 0x7680
};
__device__ __constant__ short lut_nmsedec_sig0[128] = {
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0080, 0x0080,
    0x0080, 0x0080, 0x0100, 0x0100, 0x0100, 0x0180, 0x0180, 0x0200,
    0x0200, 0x0280, 0x0280, 0x0300, 0x0300, 0x0380, 0x0400, 0x0400,
    0x0480, 0x0500, 0x0580, 0x0580, 0x0600, 0x0680, 0x0700, 0x0780,
    0x0800, 0x0880, 0x0900, 0x0980, 0x0a00, 0x0a80, 0x0b80, 0x0c00,
    0x0c80, 0x0d00, 0x0e00, 0x0e80, 0x0f00, 0x1000, 0x1080, 0x1180,
    0x1200, 0x1300, 0x1380, 0x1480, 0x1500, 0x1600, 0x1700, 0x1780,
    0x1880, 0x1980, 0x1a80, 0x1b00, 0x1c00, 0x1d00, 0x1e00, 0x1f00,
    0x2000, 0x2100, 0x2200, 0x2300, 0x2400, 0x2500, 0x2680, 0x2780,
    0x2880, 0x2980, 0x2b00, 0x2c00, 0x2d00, 0x2e80, 0x2f80, 0x3100,
    0x3200, 0x3380, 0x3480, 0x3600, 0x3700, 0x3880, 0x3a00, 0x3b00,
    0x3c80, 0x3e00, 0x3f80, 0x4080, 0x4200, 0x4380, 0x4500, 0x4680,
    0x4800, 0x4980, 0x4b00, 0x4c80, 0x4e00, 0x4f80, 0x5180, 0x5300,
    0x5480, 0x5600, 0x5800, 0x5980, 0x5b00, 0x5d00, 0x5e80, 0x6080,
    0x6200, 0x6400, 0x6580, 0x6780, 0x6900, 0x6b00, 0x6d00, 0x6e80,
    0x7080, 0x7280, 0x7480, 0x7600, 0x7800, 0x7a00, 0x7c00, 0x7e00
};
__device__ __constant__ short lut_nmsedec_ref[128] = {
    0x1800, 0x1780, 0x1700, 0x1680, 0x1600, 0x1580, 0x1500, 0x1480,
    0x1400, 0x1380, 0x1300, 0x1280, 0x1200, 0x1180, 0x1100, 0x1080,
    0x1000, 0x0f80, 0x0f00, 0x0e80, 0x0e00, 0x0d80, 0x0d00, 0x0c80,
    0x0c00, 0x0b80, 0x0b00, 0x0a80, 0x0a00, 0x0980, 0x0900, 0x0880,
    0x0800, 0x0780, 0x0700, 0x0680, 0x0600, 0x0580, 0x0500, 0x0480,
    0x0400, 0x0380, 0x0300, 0x0280, 0x0200, 0x0180, 0x0100, 0x0080,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0080, 0x0100, 0x0180, 0x0200, 0x0280, 0x0300, 0x0380,
    0x0400, 0x0480, 0x0500, 0x0580, 0x0600, 0x0680, 0x0700, 0x0780,
    0x0800, 0x0880, 0x0900, 0x0980, 0x0a00, 0x0a80, 0x0b00, 0x0b80,
    0x0c00, 0x0c80, 0x0d00, 0x0d80, 0x0e00, 0x0e80, 0x0f00, 0x0f80,
    0x1000, 0x1080, 0x1100, 0x1180, 0x1200, 0x1280, 0x1300, 0x1380,
    0x1400, 0x1480, 0x1500, 0x1580, 0x1600, 0x1680, 0x1700, 0x1780
};
__device__ __constant__ short lut_nmsedec_ref0[128] = {
    0x2000, 0x1f00, 0x1e00, 0x1d00, 0x1c00, 0x1b00, 0x1a80, 0x1980,
    0x1880, 0x1780, 0x1700, 0x1600, 0x1500, 0x1480, 0x1380, 0x1300,
    0x1200, 0x1180, 0x1080, 0x1000, 0x0f00, 0x0e80, 0x0e00, 0x0d00,
    0x0c80, 0x0c00, 0x0b80, 0x0a80, 0x0a00, 0x0980, 0x0900, 0x0880,
    0x0800, 0x0780, 0x0700, 0x0680, 0x0600, 0x0580, 0x0580, 0x0500,
    0x0480, 0x0400, 0x0400, 0x0380, 0x0300, 0x0300, 0x0280, 0x0280,
    0x0200, 0x0200, 0x0180, 0x0180, 0x0100, 0x0100, 0x0100, 0x0080,
    0x0080, 0x0080, 0x0080, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0080, 0x0080,
    0x0080, 0x0080, 0x0100, 0x0100, 0x0100, 0x0180, 0x0180, 0x0200,
    0x0200, 0x0280, 0x0280, 0x0300, 0x0300, 0x0380, 0x0400, 0x0400,
    0x0480, 0x0500, 0x0580, 0x0580, 0x0600, 0x0680, 0x0700, 0x0780,
    0x0800, 0x0880, 0x0900, 0x0980, 0x0a00, 0x0a80, 0x0b80, 0x0c00,
    0x0c80, 0x0d00, 0x0e00, 0x0e80, 0x0f00, 0x1000, 0x1080, 0x1180,
    0x1200, 0x1300, 0x1380, 0x1480, 0x1500, 0x1600, 0x1700, 0x1780,
    0x1880, 0x1980, 0x1a80, 0x1b00, 0x1c00, 0x1d00, 0x1e00, 0x1f00
};

/*
 * The copyright in this software is being made available under the 2-clauses
 * BSD License, included below. This software may be subject to other third
 * party and contributor rights, including patent rights, and no such rights
 * are granted under this license.
 *
 * Copyright (c) 2002-2014, Universite catholique de Louvain (UCL), Belgium
 * Copyright (c) 2002-2014, Professor Benoit Macq
 * Copyright (c) 2001-2003, David Janssens
 * Copyright (c) 2002-2003, Yannick Verschueren
 * Copyright (c) 2003-2007, Francois-Olivier Devaux
 * Copyright (c) 2003-2014, Antonin Descampe
 * Copyright (c) 2005, Herve Drolon, FreeImage Team
 * Copyright (c) 2007, Callum Lerwick <seg@haxxed.com>
 * Copyright (c) 2012, Carl Hetherington
 * Copyright (c) 2017, IntoPIX SA <support@intopix.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS `AS IS'
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
/* SPDX-License-Identifier: BSD-2-Clause
 * CUDA Part 1 JPEG2000 Tier-1 decoder.
 * MQ arithmetic and context semantics adapted from OpenJPEG v2.5.4.
 * Upstream copyright and license are retained above.
 * Experimental Part 1 MQ/RAW path, ROI undo and PTERM diagnostics; no HT.
 * Each one-item work-group owns bounded packed stripe flags in local memory.
 * Context tables and constant-pass/common-geometry specialization reduce the
 * work per ordered MQ decision without changing the codestream.
 */
typedef struct { uint a, c, ct, pos, synthesized; uint ctx0, ctx1, ctx2, ctx3, ctx4; } MQ;

__device__ __forceinline__ uint input_byte(const uchar *src, uint length, uint pos)
{
    return pos < length ? src[pos] : 255u;
}
__device__ __forceinline__ void bytein(MQ *m, const uchar *src, uint length)
{
    uint next = input_byte(src, length, m->pos + 1);
    if (input_byte(src, length, m->pos) == 255) {
        if (next > 143) { m->c += 0xff00; m->ct = 8; ++m->synthesized; }
        else { ++m->pos; m->c += next << 9; m->ct = 7; }
    } else { ++m->pos; m->c += next << 8; m->ct = 8; }
}
__device__ __forceinline__ uint context_state(MQ *m,uint context)
{
    uint word=context<4 ? m->ctx0 : context<8 ? m->ctx1 : context<12 ? m->ctx2 : context<16 ? m->ctx3 : m->ctx4;
    return (word >> ((context&3)*8)) & 255;
}
__device__ __forceinline__ void set_context(MQ *m,uint context,uint state)
{
    uint shift=(context&3)*8,mask=~(255u<<shift),value=state<<shift;
    if(context<4) m->ctx0=(m->ctx0&mask)|value;
    else if(context<8) m->ctx1=(m->ctx1&mask)|value;
    else if(context<12) m->ctx2=(m->ctx2&mask)|value;
    else if(context<16) m->ctx3=(m->ctx3&mask)|value;
    else m->ctx4=(m->ctx4&mask)|value;
}
__device__ __forceinline__ void reset_contexts(MQ *m)
{
    m->ctx0=8; m->ctx1=0; m->ctx2=0; m->ctx3=0; m->ctx4=(6u<<8)|(92u<<16);
}
__device__ __forceinline__ uint raw_decision(MQ *m, const uchar *src, uint length)
{
    if (!m->ct) {
        uint next = input_byte(src,length,m->pos);
        if (m->c == 255) {
            if (next > 143) { m->c = 255; m->ct = 8; }
            else { m->c = next; ++m->pos; m->ct = 7; }
        } else { m->c = next; ++m->pos; m->ct = 8; }
    }
    --m->ct;
    return (m->c >> m->ct) & 1;
}
__device__ __forceinline__ void init_segment(MQ *m, const uchar *src, uint length)
{
    m->pos = 0; m->synthesized = 0; m->c = input_byte(src, length, 0) << 16;
    bytein(m, src, length); m->c <<= 7; m->ct -= 7; m->a = 0x8000;
}
__device__ __forceinline__ uint decision(MQ *m, const uchar *src, uint length, uint context)
{
    uint state = mq_states[context_state(m,context)];
    uint qe=state&65535u, mps=(state>>16)&1u, nmps=(state>>17)&127u, nlps=state>>24;
    uint bit;
    m->a -= qe;
    if ((m->c >> 16) < qe) {
        if (m->a < qe) { bit = mps; set_context(m,context,nmps); }
        else { bit = 1 - mps; set_context(m,context,nlps); }
        m->a = qe;
    } else {
        m->c -= qe << 16;
        if (m->a & 0x8000) return mps;
        if (m->a < qe) { bit = 1 - mps; set_context(m,context,nlps); }
        else { bit = mps; set_context(m,context,nmps); }
    }
    do {
        if (!m->ct) bytein(m, src, length);
        uint shift=min((uint)(__clz(m->a)-16),m->ct);
        m->a <<= shift; m->c <<= shift; m->ct -= shift;
    } while (m->a < 0x8000);
    return bit;
}
/* Four-row stripe flags, following OpenJPEG's SIGMA/CHI/MU/PI layout.
 * Bits 0..17: significance for three columns and six rows (with vertical halo).
 * Bits 18,19,22,25,28,31: vertical sign samples, including the halo.
 * Bits 20,23,26,29: refinement; 21,24,27,30: significance-pass visits.
 * No padding words: boundary propagation is explicitly bounded. */
#define SIG 16u
#define VISITED 512u
#define REFINED 1024u
#define NEIGHBORS 495u
#define PI_ALL ((1u<<21)|(1u<<24)|(1u<<27)|(1u<<30))
/* Present the current row as significance (0..8), visited (9), refined (10). */
__device__ __forceinline__ uint sample_flags(FlagArray flags,int x,int y,int w)
{
    uint f=flags[(y>>2)*w+x] >> (3*(y&3));
    return (f&511u) | ((f>>12)&512u) | ((f>>10)&1024u);
}
__device__ __forceinline__ void mark_flag(FlagArray flags,int x,int y,int w,uint bit)
{
    flags[(y>>2)*w+x] |= bit << (3*(y&3));
}
__device__ __forceinline__ int neighbors(FlagArray flags, int x, int y, int w, int h, uint style)
{
    return (sample_flags(flags,x,y,w) & NEIGHBORS) != 0;
}
__device__ __forceinline__ uint zero_context(FlagArray flags, int x, int y, int w, int h, uint orient, uint style)
{
    return lut_ctxno_zc[orient*512+(sample_flags(flags,x,y,w)&NEIGHBORS)];
}
__device__ __forceinline__ void decode_sign(MQ *m, const uchar *src, uint length,
                 int *data, FlagArray flags,
                 int x, int y, int w, int h, int value, uint style, uint raw)
{
    uint f=sample_flags(flags,x,y,w), stripe=(y>>2)*w+x, row=y&3;
    uint packed=flags[stripe], north=row ? 19+3*(row-1) : 18;
    uint south=row<3 ? 19+3*(row+1) : 31;
    uint signs=((packed>>north)&1u)<<11 | ((packed>>south)&1u)<<14;
    if(x) signs |= ((flags[stripe-1]>>(19+3*row))&1u)<<12;
    if(x+1<w) signs |= ((flags[stripe+1]>>(19+3*row))&1u)<<13;
    f |= signs;
    uint lu=(f&170u) | ((f>>12)&1u) | ((f>>11)&4u) | ((f>>7)&16u) | ((f>>8)&64u);
    uint prediction=lut_spb[lu], context=lut_ctxno_sc[lu];
    uint sign = raw ? raw_decision(m,src,length) : decision(m,src,length,context) ^ prediction;
    data[y*w+x] = sign ? -value : value;
    flags[stripe] |= sign << (19+3*row);
    /* Propagate a single significance bit per neighbouring stripe column. */
    for(int dx=-1;dx<=1;++dx) {
        int tx=x+dx;
        if(tx<0 || tx>=w) continue;
        flags[(y>>2)*w+tx] |= 1u << (3*(row+1)+1-dx);
        if(row==0 && y>0 && !(style&8))
            flags[((y>>2)-1)*w+tx] |= 1u << (16-dx);
        if(row==3 && y+1<h)
            flags[((y>>2)+1)*w+tx] |= 1u << (1-dx);
    }
    if(row==0 && y>0 && !(style&8)) flags[stripe-w] |= sign<<31;
    if(row==3 && y+1<h) flags[stripe+w] |= sign<<18;

}

/* Constant pass arguments remove pass dispatch from coefficient loops. */
__device__ __forceinline__ void decode_pass(MQ *m,
    const uchar *src,uint length,int *data,FlagArray flags,
    int w,int h,uint orient,uint style,uint pass,uint raw,int midpoint,int value)
{
    for (int stripe = 0; stripe < h; stripe += 4) {
        int rows = min(4,h-stripe);
        for (int x = 0; x < w; ++x) {
            int start = 0, forced = 0;
            if (pass == 2 && rows == 4) {
                int aggregate = !(flags[(stripe>>2)*w+x] & (0x3ffffu|PI_ALL));
                if (aggregate) {
                    if (!decision(m,src,length,17)) continue;
                    start = (int)decision(m,src,length,18) << 1;
                    start |= decision(m,src,length,18); forced = 1;
                }
            }
            for (int j = start; j < rows; ++j) {
                int y = stripe+j, at = y*w+x;
                if (pass == 1) {
                    if ((sample_flags(flags,x,y,w) & (SIG|VISITED)) == SIG) {
                        uint context = 14 + ((sample_flags(flags,x,y,w) & REFINED) ? 2 : neighbors(flags,x,y,w,h,style) ? 1 : 0);
                        uint bit = raw ? raw_decision(m,src,length) : decision(m,src,length,context);
                        data[at] += (bit ^ (data[at] < 0)) ? midpoint : -midpoint;
                        mark_flag(flags,x,y,w,1u<<20);
                    }
                } else if (!(sample_flags(flags,x,y,w) & (SIG|VISITED))) {
                    if (pass == 0 && !neighbors(flags,x,y,w,h,style)) continue;
                    uint bit = forced ? 1 : raw ? raw_decision(m,src,length) : decision(m,src,length,zero_context(flags,x,y,w,h,orient,style));
                    forced = 0;
                    if (bit) decode_sign(m,src,length,data,flags,x,y,w,h,value,style,raw);
                    if (pass == 0) mark_flag(flags,x,y,w,1u<<21);
                }
            }
        }
    }
}

/* Descriptor: w,h,orientation,numbps,style,inputOffset,inputLength,
 * segmentOffset,segmentCount,coefficientOffset,roiShift,checkPterm.
 * Segments: length, passCount.
 * Host verifies every range before upload; each block owns disjoint scratch.
 */
__device__ __forceinline__ void decode_one(const uint *desc, const uint2 *segments,
    const uchar *input, int *data, FlagArray flags, uint *status, uint block)
{
    const uint *d = desc + block*12;
    int w = d[0], h = d[1];
    uint orient = d[2], style = d[4], offset = 0;
    status[block] = 0;
    if (style & ~63u || w <= 0 || h <= 0 || w*h > 4096 || orient > 3 || d[3] > 30 || d[10] > 30 || d[3]+d[10] > 30) {
        status[block] = 1; return;
    }
    for (int i = 0; i < w*h; ++i) data[i] = 0;
    for (int i = 0; i < w*((h+3)/4); ++i) flags[i] = 0;
    MQ m; reset_contexts(&m); m.synthesized = 0;
    int bp = d[3]+d[10]; uint pass = 2, last_length = 0;
    for (uint seg = 0; seg < d[8]; ++seg) {
        uint2 s = segments[d[7]+seg];
        last_length = s.x;
        if (offset > d[6] || s.x > d[6]-offset) { status[block] = 2; return; }
        const uchar *src = input + d[5] + offset;
        offset += s.x;
        uint raw = (style & 1) && bp <= (int)d[3]-4 && pass < 2;
        if (raw) { m.c = 0; m.ct = 0; m.pos = 0; }
        else init_segment(&m,src,s.x);
        for (uint p = 0; p < s.y && bp >= 1; ++p) {
            int midpoint = (1 << bp) >> 1, value = (1 << bp) | midpoint;
            /* The common 64x64/MQ path gives the compiler constant geometry,
             * coding style and pass. Edge blocks and all other styles stay GPU. */
            if (w==64 && h==64 && style==0) {
                if (pass==0) decode_pass(&m,src,s.x,data,flags,64,64,orient,0,0,0,midpoint,value);
                else if (pass==1) decode_pass(&m,src,s.x,data,flags,64,64,orient,0,1,0,midpoint,value);
                else decode_pass(&m,src,s.x,data,flags,64,64,orient,0,2,0,midpoint,value);
            }
            else if (pass == 0) decode_pass(&m,src,s.x,data,flags,w,h,orient,style,0,raw,midpoint,value);
            else if (pass == 1) decode_pass(&m,src,s.x,data,flags,w,h,orient,style,1,raw,midpoint,value);
            else decode_pass(&m,src,s.x,data,flags,w,h,orient,style,2,0,midpoint,value);
            if (pass == 2) {
                for (int i = 0; i < w*((h+3)/4); ++i) flags[i] &= ~PI_ALL;
                if (style & 32) {
                    uint symbol = 0;
                    for (int i = 0; i < 4; ++i) symbol = (symbol << 1) | decision(&m,src,s.x,18);
                    /* Upstream consumes but does not reject a bad SEGSYM.
                     * Preserve partial-quality output; retain a diagnostic bit. */
                    if (symbol != 10) status[block] |= 256;
                }
            }
            if ((style & 2) && !raw) reset_contexts(&m);
            if (++pass == 3) { pass = 0; --bp; }
        }
    }
    if (d[11] && d[8]) {
        if (m.pos + 2 < last_length) status[block] |= 512;
        else if (m.synthesized > 2) status[block] |= 1024;
    }
    if (d[10]) {
        int threshold = 1 << d[10];
        for (int i = 0; i < w*h; ++i) {
            int magnitude = abs(data[i]);
            if (magnitude >= threshold) {
                magnitude >>= d[10];
                data[i] = data[i] < 0 ? -magnitude : magnitude;
            }
        }
    }
}

/* Each serial arithmetic coder owns a CUDA block and shared packed flags.
 * Independent streams expose parallelism across tiles; no cross-block barriers. */
extern "C" __global__ __launch_bounds__(1) void decode_blocks(const uint *desc, const uint2 *segments,
    const uchar *input, int *output,
    uint *status, uint count, uint first_block)
{
    uint block=first_block+blockIdx.x;
    if(block>=count) return;
    extern __shared__ unsigned workspace[];
    const uint *d=desc+block*12;
    int *data=output+d[9];
    decode_one(desc,segments,input,data,FlagArray{workspace},status,block);

}

/*
 * The copyright in this software is being made available under the 2-clauses
 * BSD License, included below. This software may be subject to other third
 * party and contributor rights, including patent rights, and no such rights
 * are granted under this license.
 *
 * Copyright (c) 2002-2014, Universite catholique de Louvain (UCL), Belgium
 * Copyright (c) 2002-2014, Professor Benoit Macq
 * Copyright (c) 2001-2003, David Janssens
 * Copyright (c) 2002-2003, Yannick Verschueren
 * Copyright (c) 2003-2007, Francois-Olivier Devaux
 * Copyright (c) 2003-2014, Antonin Descampe
 * Copyright (c) 2005, Herve Drolon, FreeImage Team
 * Copyright (c) 2007, Jonathan Ballard <dzonatas@dzonux.net>
 * Copyright (c) 2007, Callum Lerwick <seg@haxxed.com>
 * Copyright (c) 2017, IntoPIX SA <support@intopix.com>
 * Copyright (c) 2006-2007, Parvatha Elangovan
 * Copyright (c) 2008, 2011-2012, Centre National d'Etudes Spatiales (CNES), FR
 * Copyright (c) 2012, CS Systemes d'Information, France
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS `AS IS'
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
/* SPDX-License-Identifier: BSD-2-Clause
 * Reconstruction semantics follow OpenJPEG v2.5.4 dwt.c/mct.c/tcd.c.
 * See upstream notices in the source tree and embedded kernel bundle.
 */


extern "C" __global__ void place_blocks(const uint *desc, const uint4 *place,
                           const float *scale, const int *coeff,
                           int *planes, uint count, uint reversible)
{
    uint b = blockIdx.x;
    if (b >= count) return;
    uint4 p = place[b]; /* destination, stride, width, height */
    uint offset = desc[b*12+9];
    for (uint at=threadIdx.x; at<p.z*p.w; at+=64) {
        uint y=at/p.z, x=at-y*p.z;
        int v = coeff[offset+y*p.z+x];
        uint target = p.x+y*p.y+x;
        if (reversible) planes[target] = v/2;
        else ((float*)planes)[target] = __int2float_rn(v)*scale[b];
    }
}

/* A 64-thread block cooperates on one line in shared memory. Barriers
 * separate lifting phases; the CUDA stream orders the two axes. */
extern "C" __global__ void inverse_line(int *planes, 
                           uint base, uint stride, uint length, uint lines,
                           uint low_count, uint parity, uint vertical, uint reversible)
{
    extern __shared__ int tmp[];
    uint line = blockIdx.x;
    uint lane = threadIdx.x;
    if (line >= lines) return;
    uint origin = base + (vertical ? line : line*stride);
    uint step = vertical ? stride : 1;
    float *f = (float*)tmp;
    for (uint i=lane; i<length; i+=64) {
        uint source = ((i+parity)&1) ? low_count+i/2 : i/2;
        tmp[i] = planes[origin+source*step];
    }
    __syncthreads();
    if (reversible) {
        if (length == 1) { if (parity && lane == 0) tmp[0] /= 2; }
        else {
            for (uint i=parity+2*lane; i<length; i+=128) {
                uint l=i ? i-1 : 1, r=i+1<length ? i+1 : i-1;
                tmp[i] -= (tmp[l]+tmp[r]+2)>>2;
            }
            __syncthreads();
            for (uint i=1-parity+2*lane; i<length; i+=128) {
                uint l=i ? i-1 : 1, r=i+1<length ? i+1 : i-1;
                tmp[i] += (tmp[l]+tmp[r])>>1;
            }
        }
    } else if (length > 1) {
        for (uint i=lane; i<length; i+=64)
            f[i] *= ((i+parity)&1) ? 1.625732422f : 1.230174105f;
        __syncthreads();
        const float lift[4] = {-0.443506852f,-0.882911075f,0.052980118f,1.586134342f};
        for (uint phase=0; phase<4; ++phase) {
            for (uint i=((phase&1) ? 1-parity : parity)+2*lane; i<length; i+=128) {
                uint l=i ? i-1 : 1, r=i+1<length ? i+1 : i-1;
                f[i] = f[i] + (f[l]+f[r])*lift[phase];
            }
            __syncthreads();
        }
    }
    __syncthreads();
    for (uint i=lane; i<length; i+=64) planes[origin+i*step] = tmp[i];
}

extern "C" __global__ void finish_pixels(int *planes, uint samples, uint components,
                            uint mct, uint reversible, uint precision, uint is_signed,
                            int dc_shift)
{
    uint i=(blockIdx.x*blockDim.x+threadIdx.x);
    if (i>=samples) return;
    int lo=is_signed ? -(1<<(precision-1)) : 0;
    int hi=is_signed ? (1<<(precision-1))-1 : (1<<precision)-1;
    if (mct && components>=3) {
        if (reversible) {
            int y=planes[i], u=planes[samples+i], v=planes[2*samples+i];
            int g=y-((u+v)>>2);
            planes[i]=v+g; planes[samples+i]=g; planes[2*samples+i]=u+g;
        } else {
            float *p=(float*)planes;
            float y=p[i], u=p[samples+i], v=p[2*samples+i];
            p[i]=y+v*1.402f;
            p[samples+i]=(y-u*0.34413f)-v*0.71414f;
            p[2*samples+i]=y+u*1.772f;
        }
    }
    for (uint c=0;c<components;++c) {
        uint at=c*samples+i;
        long long v;
        if (reversible) v=planes[at];
        else v=__float2ll_rn(((float*)planes)[at]);
        planes[at]=(int)min(max(v+(long long)dc_shift,(long long)lo),(long long)hi);
    }
}
